google:
  client:
    id: {}
    secret: {}
  redirect:
    uri: http://localhost:8080/redirect

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR